# Generated by Django 4.2.7 on 2024-05-01 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_likes_meme_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_memes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
