# Generated by Django 4.2.7 on 2024-03-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allAuth', '0002_userprofile_firstname_userprofile_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastName',
        ),
    ]
